version: '3'

services:
  wgetbash:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5008:8000"
    restart: always
    container_name: "wgetbash-container"
    environment:
      - ALLOWED_HOSTS= localhost 127.0.0.1
      - TOKEN_TG=${TOKEN_TG}
      - HOST_DNS=${HOST_DNS}
      - BOT_NAME=${BOT_NAME}
    volumes:
      - .:/code
      - ./sqlite:/sqlite
      - ./api/static:/api/static


# TOKEN_TG = 
# HOST_DNS = 
# BOT_NAME = 