# Generated by Django 5.0.6 on 2024-06-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=56)),
                ('author', models.CharField(default='no-auth', max_length=56)),
                ('text', models.TextField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(to='api.telegramusers')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=56, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telegramusers')),
                ('scripts', models.ManyToManyField(to='api.scripts')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
