# Generated by Django 5.0.6 on 2024-06-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mainpage_alter_templates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='youtube_id',
            field=models.CharField(default='jfKfPfyJRdk', max_length=56),
        ),
    ]
